name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build YYTK Core
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild .\YYToolkit\YYToolkit.vcxproj /property:Configuration=Release /property:PlatformTarget=x86
      
    - name: Build YYTK ExamplePlugin
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild .\Plugins\ExamplePlugin\ExamplePlugin.vcxproj /property:Configuration=Release /property:PlatformTarget=x86

      - name: Build Chapter2 Hard Mode Plugin
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild .\Plugins\Chapter2_HardMode\Chapter2_HardMode.vcxproj /property:Configuration=Release /property:PlatformTarget=x86
      
    - name: Build YYLauncher
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild .\Launcher\Launcher.csproj /property:Configuration=Release /property:PlatformTarget=x86
      
    - name: Upload YYTK Core as artifact
      uses: actions/upload-artifact@v2
      with:
        name: YYTK-Core
        path: .\YYToolkit\Build\Core\Release\YYToolkit.dll
      
    - name: Upload ExamplePlugin as artifact
      uses: actions/upload-artifact@v2
      with:
        name: ExamplePlugin
        path: .\YYToolkit\Build\Plugins\Example\Release\ExamplePlugin.dll
        
    - name: Upload Hard Mode as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HardMode
        path: .\YYToolkit\Build\Plugins\Hard Mode\Release\Chapter2_HardMode.dll
        
    - name: Upload YYLauncher as artifact
      uses: actions/upload-artifact@v2
      with:
        name: YYLauncher
        path: .\Launcher\bin\Release\Launcher.exe
